services:
  client:
    container_name: recipe_planner_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Värd:Container (React + Nginx exponerar port 80)
    networks:
      - recipe_net
    env_file:
      - ./client/.env

  backend:
    container_name: recipe_planner_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Express kör på port 3000
    networks:
      - recipe_net
    env_file:
      - ./server/.env


networks:
  recipe_net:
    driver: bridge