services:
  client:
    container_name: test_client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_REACT_APP_API_URL: $API_URL
        VITE_CLERK_PUBLISHABLE_KEY: $CLERK_KEY
    ports:
      - "3000:80"  # Värd:Container (React + Nginx exponerar port 80)
    networks:
      - test_net
    restart: always
    environment:
      VITE_REACT_APP_API_URL: $API_URL
      VITE_CLERK_PUBLISHABLE_KEY: $CLERK_KEY

  backend:
    container_name: test_client_backend
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        SPOONACULAR_BASE_API: $SPOONACULAR_API
        SPOONACULAR_APIKEY: $SPOONACULAR_APIKEY
        DB_CONNECTION_STRING: $MONGODB_STRING
        CLERK_SECRET_KEY: $CLERK_SECRET
        CLERK_PUBLISHABLE_KEY: $CLERK_KEY
        SESSION_NAME: $SESSION_NAME
        SESSION_SECRET: $SESSION_SECRET
    ports:
      - "8080:5000"  # Express kör på port 3000
    networks:
      - test_net
    environment:
      SPOONACULAR_BASE_API: $SPOONACULAR_API
      SPOONACULAR_APIKEY: $SPOONACULAR_APIKEY
      DB_CONNECTION_STRING: $MONGODB_STRING
      CLERK_SECRET_KEY: $CLERK_SECRET
      CLERK_PUBLISHABLE_KEY: $CLERK_KEY
      SESSION_NAME: $SESSION_NAME
      SESSION_SECRET: $SESSION_SECRET
    restart: always

networks:
  test_net:
    driver: bridge