services:

  client:
    container_name: recipe_planner_client
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - "3000:80"  # Värd:Container (React + Nginx exponerar port 80)
    networks:
      - recipe_net
    restart: always

  backend:
    container_name: recipe_planner_backend
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - "8080:5000"  # Express kör på port 3000
    networks:
      - recipe_net
    restart: always

networks:
  recipe_net:
    driver: bridge